# The below will look in Vault for /path/to/your/secret and will return the key 'secretkey', it will then base64 encode that value.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-replacer-example-secret
data:
  sample-secret: <secret:path/data/to/your/secret~secretkey|base64>
type: Opaque
