apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-replacer-example-secret
data:
  sample-secret: {{ .Values.secret.sample-secret | b64enc }}
  sample-secret-quoted: {{ .Values.secret.sample-secret-quoted | b64enc | quote }}
type: Opaque
